---
abstract: 'provides a clean-room reimplementation of common::sense'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.016, CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alt-common-sense-TOBYINK
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
  package:
    - common::sense
optional_features: {}
provides:
  Alt::common::sense::TOBYINK:
    file: lib/Alt/common/sense/TOBYINK.pm
    version: '0.001'
requires:
  perl: '5.006'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Alt-common-sense-TOBYINK/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Alt-common-sense-TOBYINK
  homepage: https://metacpan.org/release/Alt-common-sense-TOBYINK
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-alt-common-sense-tobyink.git
version: '0.001'
